# swagger
springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: true # deshabilitar para produccion: false

#server
server:
  port: 8081

#spring
spring:
  application:
    name: customer

#eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

